language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install
  - ./bin/jackrabbit.sh
  - php bin/jackrabbit.php
  - 
script: 
    - time ./bin/runtests.sh -i -a
    - phpunit
