language: php

php:
  - 5.4

before_script:
  - composer install --dev
  - ./vendor/sulu/test-bundle/Sulu/Bundle/TestBundle/Resources/bin/travis.sh
  - ./vendor/symfony-cmf/testing/bin/console sulu:webspace:init

script: phpunit --process-isolation --coverage-text
